---

require:
- rubocop-rake

AllCops:
  SuggestExtensions: false
  NewCops: enable
  ExtraDetails: false
  Exclude:
  - ".git/**/*"
  - bin/**/*
  - tmp/**/*
  - sandbox/**/*
  - db/**/*.rb

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Exclude:
  - "/web/views/**/*.rb"
  - "/web/components/**/*.rb"

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
  - web/view/**/*.rb
  - web/component/**/*.rb
  BracesRequiredMethods:
  - let
  - let!
  - Given
  - Given!
  - When
  - Then
  - And

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/KeywordParametersOrder:
  Enabled: false

Style/RedundantInitialize:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  Enabled: false
