---
version: "3.7"

x-build-common: &build-common
  build:
    context: .
    dockerfile: Dockerfile
    target: development

x-app-common: &app-common
  stdin_open: true
  tty: true
  entrypoint: script/docker-entrypoint.sh
  volumes:
    - .:/app
    - bundler:/bundler

services:
  web:
    <<: [*build-common, *app-common]
    command: rerun --pattern **/*.{rb,ru,yml} -- bundle exec rackup --host=0.0.0.0
    ports:
      - 9292:9292
    environment:
      ENVIRONMENT: development
      HISTFILE: /app/.zsh_history

  guard:
    <<: [*build-common, *app-common]
    depends_on:
      - web
    command: bundle exec guard
    ports:
      - 35729:35729

  tailwindcss:
    <<: [*build-common, *app-common]
    entrypoint: script/docker-entrypoint-tailwind.sh
    command: npx tailwindcss -i ./web/assets/index.css -o ./assets/css/index.css --watch
    volumes:
      - .:/app

volumes:
  bundler:
