---
x-build-common: &build-common
  build:
    context: .
    dockerfile: Dockerfile
    target: development

x-app-common: &app-common
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - bundler:/bundler

services:
  app:
    <<: [*build-common, *app-common]
    stdin_open: true
    tty: true
    entrypoint: script/docker-entrypoint.sh
    environment:
      ENVIRONMENT: development
      HISTFILE: /app/.zsh_history

volumes:
  bundler:
