---
version: "3.7"

x-build-common: &build-common
  build:
    context: .
    dockerfile: Dockerfile
    target: development

x-app-common: &app-common
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - bundler:/bundler

services:
  web:
    <<: [*build-common, *app-common]
    command: "rerun --pattern **/*.{rb,ru,yml} -- bundle exec rackup --host=0.0.0.0 --pid ./server.pid"
    tty: true
    stdin_open: true
    entrypoint: script/docker-entrypoint.sh
    depends_on:
      - tailwindcss
    environment:
      ENVIRONMENT_NAME: development
      HISTFILE: /app/.zsh_history
    expose:
      - 9292
    ports:
      - "9292:9292"
    volumes:
      - .:/app
      - bundler:/bundler

  tailwindcss:
    <<: [*build-common, *app-common]
    entrypoint: script/docker-entrypoint-tailwind.sh
    command: "npx tailwindcss -i ./web/assets/index.css -o ./assets/css/index.css --watch"
    volumes:
      - .:/app

  esbuild:
    <<: [*build-common, *app-common]
    entrypoint: script/docker-entrypoint-tailwind.sh
    command: "yarn esbuild web/assets/js/index.js --bundle --watch --outfile=assets/js/index.js"
    volumes:
      - .:/app

  guard:
    <<: [*build-common, *app-common]
    depends_on:
      - web
    command: bundle exec guard --force-polling --latency=0.5
    ports:
      - "35729:35729"

volumes:
  bundler:
